version: '3'
services:

  memory_e2e:
    image: cypress/included:3.2.0
    container_name: memory_e2e
    working_dir: /e2e
    volumes:
      - ./e2e/cypress:/e2e
    network_mode: host
    entrypoint: ''
    command: sh
    tty: true